// Auto-generated player data - IPL 2026 squads + auction pool
// Format: [name, country, countryCode, role, basePrice, category, team2026, isCapped]

const CRICKETER_DATA = [
  // === CSK ===
  ["Ruturaj Gaikwad", "India", "IN", "batsman", 200, "marquee", "csk", true],
  ["MS Dhoni", "India", "IN", "wicket-keeper", 200, "marquee", "csk", false],
  ["Sanju Samson", "India", "IN", "wicket-keeper", 200, "marquee", "csk", true],
  ["Shivam Dube", "India", "IN", "all-rounder", 150, "all-rounder", "csk", true],
  ["Jamie Overton", "England", "GB", "all-rounder", 150, "all-rounder", "csk", true],
  ["Khaleel Ahmed", "India", "IN", "bowler", 100, "bowler", "csk", true],
  ["Noor Ahmad", "Afghanistan", "AF", "bowler", 75, "bowler", "csk", true],
  ["Dewald Brevis", "South Africa", "ZA", "batsman", 100, "batsman", "csk", true],
  ["Ayush Mhatre", "India", "IN", "batsman", 30, "uncapped", "csk", false],
  ["Kartik Sharma", "India", "IN", "batsman", 75, "uncapped", "csk", false],
  ["Sarfaraz Khan", "India", "IN", "batsman", 100, "batsman", "csk", true],
  ["Urvil Patel", "India", "IN", "batsman", 30, "uncapped", "csk", false],
  ["Ramakrishna Ghosh", "India", "IN", "all-rounder", 30, "uncapped", "csk", false],
  ["Prashant Veer", "India", "IN", "all-rounder", 30, "uncapped", "csk", false],
  ["Matthew Short", "Australia", "AU", "all-rounder", 100, "all-rounder", "csk", true],
  ["Aman Khan", "India", "IN", "all-rounder", 30, "uncapped", "csk", false],
  ["Zak Foulkes", "Australia", "AU", "bowler", 30, "uncapped", "csk", false],
  ["Anshul Kamboj", "India", "IN", "bowler", 30, "uncapped", "csk", false],
  ["Mukesh Choudhary", "India", "IN", "bowler", 50, "bowler", "csk", true],
  ["Shreyas Gopal", "India", "IN", "bowler", 50, "bowler", "csk", true],
  ["Gurjapneet Singh", "India", "IN", "bowler", 30, "uncapped", "csk", false],
  ["Akeal Hosein", "West Indies", "WI", "all-rounder", 75, "all-rounder", "csk", true],
  ["Matt Henry", "New Zealand", "NZ", "bowler", 100, "bowler", "csk", true],
  ["Rahul Chahar", "India", "IN", "bowler", 75, "bowler", "csk", true],
  ["Spencer Johnson", "Australia", "AU", "bowler", 100, "bowler", "csk", true],
  // === MI ===
  ["Rohit Sharma", "India", "IN", "batsman", 200, "marquee", "mi", true],
  ["Suryakumar Yadav", "India", "IN", "batsman", 200, "marquee", "mi", true],
  ["Jasprit Bumrah", "India", "IN", "bowler", 200, "marquee", "mi", true],
  ["Hardik Pandya", "India", "IN", "all-rounder", 200, "marquee", "mi", true],
  ["Tilak Varma", "India", "IN", "batsman", 150, "batsman", "mi", true],
  ["Sherfane Rutherford", "West Indies", "WI", "batsman", 75, "batsman", "mi", true],
  ["Robin Minz", "India", "IN", "wicket-keeper", 30, "uncapped", "mi", false],
  ["Ryan Rickelton", "South Africa", "ZA", "batsman", 75, "batsman", "mi", true],
  ["Quinton de Kock", "South Africa", "ZA", "wicket-keeper", 150, "wicket-keeper", "mi", true],
  ["Danish Malewar", "India", "IN", "batsman", 30, "uncapped", "mi", false],
  ["Ruchit Ahir", "India", "IN", "batsman", 30, "uncapped", "mi", false],
  ["Naman Dhir", "India", "IN", "all-rounder", 30, "uncapped", "mi", false],
  ["Mitchell Santner", "New Zealand", "NZ", "all-rounder", 100, "all-rounder", "mi", true],
  ["Raj Angad Bawa", "India", "IN", "all-rounder", 30, "uncapped", "mi", false],
  ["Mayank Rawat", "India", "IN", "all-rounder", 30, "uncapped", "mi", false],
  ["Corbin Bosch", "South Africa", "ZA", "all-rounder", 75, "all-rounder", "mi", true],
  ["Will Jacks", "England", "GB", "all-rounder", 150, "all-rounder", "mi", true],
  ["Shardul Thakur", "India", "IN", "all-rounder", 100, "all-rounder", "mi", true],
  ["Mahipal Lomror", "India", "IN", "all-rounder", 50, "all-rounder", "mi", true],
  ["Krish Bhagat", "India", "IN", "all-rounder", 30, "uncapped", "mi", false],
  ["Atharva Ankolekar", "India", "IN", "all-rounder", 30, "uncapped", "mi", false],
  ["Trent Boult", "New Zealand", "NZ", "bowler", 150, "bowler", "mi", true],
  ["Deepak Chahar", "India", "IN", "bowler", 100, "bowler", "mi", true],
  ["Mayank Markande", "India", "IN", "bowler", 30, "uncapped", "mi", false],
  ["Ashwani Kumar", "India", "IN", "bowler", 30, "uncapped", "mi", false],
  ["Raghu Sharma", "India", "IN", "bowler", 30, "uncapped", "mi", false],
  ["Mohammad Izhar", "India", "IN", "bowler", 30, "uncapped", "mi", false],
  ["Allah Ghazanfar", "Afghanistan", "AF", "bowler", 50, "bowler", "mi", true],
  ["Keshav Maharaj", "South Africa", "ZA", "bowler", 100, "bowler", "mi", true],
  // === RCB ===
  ["Virat Kohli", "India", "IN", "batsman", 200, "marquee", "rcb", true],
  ["Rajat Patidar", "India", "IN", "batsman", 150, "marquee", "rcb", true],
  ["Phil Salt", "England", "GB", "wicket-keeper", 200, "marquee", "rcb", true],
  ["Devdutt Padikkal", "India", "IN", "batsman", 100, "batsman", "rcb", true],
  ["Jitesh Sharma", "India", "IN", "wicket-keeper", 75, "wicket-keeper", "rcb", true],
  ["Jordan Cox", "England", "GB", "wicket-keeper", 50, "wicket-keeper", "rcb", true],
  ["Krunal Pandya", "India", "IN", "all-rounder", 100, "all-rounder", "rcb", true],
  ["Swapnil Singh", "India", "IN", "all-rounder", 30, "uncapped", "rcb", false],
  ["Tim David", "Australia", "AU", "all-rounder", 150, "all-rounder", "rcb", true],
  ["Romario Shepherd", "West Indies", "WI", "all-rounder", 75, "all-rounder", "rcb", true],
  ["Jacob Bethell", "England", "GB", "all-rounder", 100, "all-rounder", "rcb", true],
  ["Venkatesh Iyer", "India", "IN", "all-rounder", 100, "all-rounder", "rcb", true],
  ["Satvik Deswal", "India", "IN", "all-rounder", 30, "uncapped", "rcb", false],
  ["Mangesh Yadav", "India", "IN", "bowler", 30, "uncapped", "rcb", false],
  ["Vicky Ostwal", "India", "IN", "bowler", 30, "uncapped", "rcb", false],
  ["Vihaan Malhotra", "India", "IN", "batsman", 30, "uncapped", "rcb", false],
  ["Kanishk Chouhan", "India", "IN", "all-rounder", 30, "uncapped", "rcb", false],
  ["Josh Hazlewood", "Australia", "AU", "bowler", 150, "bowler", "rcb", true],
  ["Rasikh Dar", "India", "IN", "bowler", 50, "bowler", "rcb", true],
  ["Suyash Sharma", "India", "IN", "bowler", 30, "uncapped", "rcb", false],
  ["Bhuvneshwar Kumar", "India", "IN", "bowler", 100, "bowler", "rcb", true],
  ["Abhinandan Singh", "India", "IN", "bowler", 30, "uncapped", "rcb", false],
  ["Jacob Duffy", "New Zealand", "NZ", "bowler", 50, "bowler", "rcb", true],
  ["Richard Gleeson", "England", "GB", "bowler", 50, "bowler", "rcb", true],
  ["Yash Dayal", "India", "IN", "bowler", 75, "bowler", "rcb", true],
  // === KKR ===
  ["Rinku Singh", "India", "IN", "batsman", 200, "marquee", "kkr", true],
  ["Sunil Narine", "West Indies", "WI", "all-rounder", 200, "marquee", "kkr", true],
  ["Varun Chakaravarthy", "India", "IN", "bowler", 200, "marquee", "kkr", true],
  ["Ajinkya Rahane", "India", "IN", "batsman", 100, "batsman", "kkr", true],
  ["Angkrish Raghuvanshi", "India", "IN", "batsman", 30, "uncapped", "kkr", false],
  ["Manish Pandey", "India", "IN", "batsman", 75, "batsman", "kkr", true],
  ["Finn Allen", "New Zealand", "NZ", "batsman", 75, "batsman", "kkr", true],
  ["Tejasvi Singh", "India", "IN", "batsman", 30, "uncapped", "kkr", false],
  ["Rahul Tripathi", "India", "IN", "batsman", 75, "batsman", "kkr", true],
  ["Tim Seifert", "New Zealand", "NZ", "wicket-keeper", 50, "wicket-keeper", "kkr", true],
  ["Rovman Powell", "West Indies", "WI", "batsman", 75, "batsman", "kkr", true],
  ["Anukul Roy", "India", "IN", "all-rounder", 30, "uncapped", "kkr", false],
  ["Cameron Green", "Australia", "AU", "all-rounder", 200, "marquee", "kkr", true],
  ["Sarthak Ranjan", "India", "IN", "all-rounder", 30, "uncapped", "kkr", false],
  ["Daksh Kamra", "India", "IN", "all-rounder", 30, "uncapped", "kkr", false],
  ["Rachin Ravindra", "New Zealand", "NZ", "all-rounder", 100, "all-rounder", "kkr", true],
  ["Ramandeep Singh", "India", "IN", "all-rounder", 50, "all-rounder", "kkr", true],
  ["Blessing Muzarabani", "Zimbabwe", "ZW", "bowler", 75, "bowler", "kkr", true],
  ["Vaibhav Arora", "India", "IN", "bowler", 50, "bowler", "kkr", true],
  ["Matheesha Pathirana", "Sri Lanka", "LK", "bowler", 150, "bowler", "kkr", true],
  ["Kartik Tyagi", "India", "IN", "bowler", 50, "bowler", "kkr", true],
  ["Prashant Solanki", "India", "IN", "bowler", 30, "uncapped", "kkr", false],
  ["Saurabh Dubey", "India", "IN", "bowler", 30, "uncapped", "kkr", false],
  ["Navdeep Saini", "India", "IN", "bowler", 50, "bowler", "kkr", true],
  ["Umran Malik", "India", "IN", "bowler", 75, "bowler", "kkr", true],
  // === DC ===
  ["KL Rahul", "India", "IN", "batsman", 200, "marquee", "dc", true],
  ["Axar Patel", "India", "IN", "all-rounder", 200, "marquee", "dc", true],
  ["Mitchell Starc", "Australia", "AU", "bowler", 200, "marquee", "dc", true],
  ["Kuldeep Yadav", "India", "IN", "bowler", 150, "marquee", "dc", true],
  ["Karun Nair", "India", "IN", "batsman", 100, "batsman", "dc", true],
  ["David Miller", "South Africa", "ZA", "batsman", 100, "batsman", "dc", true],
  ["Ben Duckett", "England", "GB", "batsman", 75, "batsman", "dc", true],
  ["Pathum Nissanka", "Sri Lanka", "LK", "batsman", 75, "batsman", "dc", true],
  ["Sahil Parakh", "India", "IN", "batsman", 30, "uncapped", "dc", false],
  ["Prithvi Shaw", "India", "IN", "batsman", 75, "batsman", "dc", true],
  ["Abishek Porel", "India", "IN", "wicket-keeper", 50, "wicket-keeper", "dc", true],
  ["Tristan Stubbs", "South Africa", "ZA", "batsman", 75, "batsman", "dc", true],
  ["Sameer Rizvi", "India", "IN", "all-rounder", 30, "uncapped", "dc", false],
  ["Ashutosh Sharma", "India", "IN", "all-rounder", 30, "uncapped", "dc", false],
  ["Vipraj Nigam", "India", "IN", "all-rounder", 30, "uncapped", "dc", false],
  ["Ajay Mandal", "India", "IN", "all-rounder", 30, "uncapped", "dc", false],
  ["Tripurana Vijay", "India", "IN", "all-rounder", 30, "uncapped", "dc", false],
  ["Madhav Tiwari", "India", "IN", "all-rounder", 30, "uncapped", "dc", false],
  ["Nitish Rana", "India", "IN", "batsman", 75, "batsman", "dc", true],
  ["T Natarajan", "India", "IN", "bowler", 100, "bowler", "dc", true],
  ["Mukesh Kumar", "India", "IN", "bowler", 75, "bowler", "dc", true],
  ["Dushmantha Chameera", "Sri Lanka", "LK", "bowler", 75, "bowler", "dc", true],
  ["Auqib Nabi", "India", "IN", "bowler", 30, "uncapped", "dc", false],
  ["Lungisani Ngidi", "South Africa", "ZA", "bowler", 100, "bowler", "dc", true],
  ["Kyle Jamieson", "New Zealand", "NZ", "bowler", 100, "bowler", "dc", true],
  // === PBKS ===
  ["Shreyas Iyer", "India", "IN", "batsman", 200, "marquee", "pbks", true],
  ["Arshdeep Singh", "India", "IN", "bowler", 200, "marquee", "pbks", true],
  ["Marcus Stoinis", "Australia", "AU", "all-rounder", 200, "marquee", "pbks", true],
  ["Yuzvendra Chahal", "India", "IN", "bowler", 150, "marquee", "pbks", true],
  ["Nehal Wadhera", "India", "IN", "batsman", 50, "batsman", "pbks", true],
  ["Harnoor Pannu", "India", "IN", "batsman", 30, "uncapped", "pbks", false],
  ["Pyla Avinash", "India", "IN", "batsman", 30, "uncapped", "pbks", false],
  ["Prabhsimran Singh", "India", "IN", "wicket-keeper", 50, "wicket-keeper", "pbks", true],
  ["Shashank Singh", "India", "IN", "all-rounder", 50, "all-rounder", "pbks", true],
  ["Vishnu Vinod", "India", "IN", "wicket-keeper", 30, "wicket-keeper", "pbks", false],
  ["Priyansh Arya", "India", "IN", "batsman", 30, "uncapped", "pbks", false],
  ["Harpreet Brar", "India", "IN", "all-rounder", 50, "all-rounder", "pbks", true],
  ["Marco Jansen", "South Africa", "ZA", "all-rounder", 150, "all-rounder", "pbks", true],
  ["Azmatullah Omarzai", "Afghanistan", "AF", "all-rounder", 100, "all-rounder", "pbks", true],
  ["Musheer Khan", "India", "IN", "all-rounder", 75, "all-rounder", "pbks", true],
  ["Suryansh Shedge", "India", "IN", "all-rounder", 30, "uncapped", "pbks", false],
  ["Mitch Owen", "Australia", "AU", "all-rounder", 50, "all-rounder", "pbks", true],
  ["Cooper Connolly", "Australia", "AU", "all-rounder", 50, "all-rounder", "pbks", true],
  ["Ben Dwarshuis", "Australia", "AU", "bowler", 50, "bowler", "pbks", true],
  ["Vyshak Vijaykumar", "India", "IN", "bowler", 50, "bowler", "pbks", true],
  ["Yash Thakur", "India", "IN", "bowler", 50, "bowler", "pbks", true],
  ["Xavier Bartlett", "Australia", "AU", "bowler", 75, "bowler", "pbks", true],
  ["Pravin Dubey", "India", "IN", "bowler", 30, "uncapped", "pbks", false],
  ["Vishal Nishad", "India", "IN", "bowler", 30, "uncapped", "pbks", false],
  ["Lockie Ferguson", "New Zealand", "NZ", "bowler", 150, "bowler", "pbks", true],
  // === RR ===
  ["Yashasvi Jaiswal", "India", "IN", "batsman", 200, "marquee", "rr", true],
  ["Riyan Parag", "India", "IN", "all-rounder", 200, "marquee", "rr", true],
  ["Jofra Archer", "England", "GB", "bowler", 200, "marquee", "rr", true],
  ["Ravindra Jadeja", "India", "IN", "all-rounder", 200, "marquee", "rr", true],
  ["Shimron Hetmyer", "West Indies", "WI", "batsman", 75, "batsman", "rr", true],
  ["Shubham Dubey", "India", "IN", "batsman", 30, "uncapped", "rr", false],
  ["Vaibhav Sooryavanshi", "India", "IN", "batsman", 30, "uncapped", "rr", false],
  ["Aman Rao Perala", "India", "IN", "batsman", 30, "uncapped", "rr", false],
  ["Sam Curran", "England", "GB", "all-rounder", 150, "all-rounder", "rr", true],
  ["Yudhvir Singh Charak", "India", "IN", "all-rounder", 30, "uncapped", "rr", false],
  ["Dasun Shanaka", "Sri Lanka", "LK", "all-rounder", 75, "all-rounder", "rr", true],
  ["Vignesh Puthur", "India", "IN", "all-rounder", 30, "uncapped", "rr", false],
  ["Brijesh Sharma", "India", "IN", "all-rounder", 30, "uncapped", "rr", false],
  ["Dhruv Jurel", "India", "IN", "wicket-keeper", 100, "wicket-keeper", "rr", true],
  ["Donovan Ferreira", "South Africa", "ZA", "wicket-keeper", 50, "wicket-keeper", "rr", true],
  ["Lhuan-Dre Pretorius", "South Africa", "ZA", "all-rounder", 50, "all-rounder", "rr", true],
  ["Ravi Singh", "India", "IN", "wicket-keeper", 30, "uncapped", "rr", false],
  ["Ravi Bishnoi", "India", "IN", "bowler", 100, "bowler", "rr", true],
  ["Sandeep Sharma", "India", "IN", "bowler", 50, "bowler", "rr", true],
  ["Tushar Deshpande", "India", "IN", "bowler", 75, "bowler", "rr", true],
  ["Kuldeep Sen", "India", "IN", "bowler", 50, "bowler", "rr", true],
  ["Kwena Maphaka", "South Africa", "ZA", "bowler", 50, "bowler", "rr", true],
  ["Nandre Burger", "South Africa", "ZA", "bowler", 50, "bowler", "rr", true],
  ["Adam Milne", "New Zealand", "NZ", "bowler", 50, "bowler", "rr", true],
  ["Sushant Mishra", "India", "IN", "bowler", 30, "uncapped", "rr", false],
  ["Yash Raj Punja", "India", "IN", "bowler", 30, "uncapped", "rr", false],
  // === SRH ===
  ["Pat Cummins", "Australia", "AU", "bowler", 200, "marquee", "srh", true],
  ["Travis Head", "Australia", "AU", "batsman", 200, "marquee", "srh", true],
  ["Heinrich Klaasen", "South Africa", "ZA", "wicket-keeper", 200, "marquee", "srh", true],
  ["Abhishek Sharma", "India", "IN", "all-rounder", 150, "marquee", "srh", true],
  ["Nitish Kumar Reddy", "India", "IN", "all-rounder", 100, "all-rounder", "srh", true],
  ["Liam Livingstone", "England", "GB", "all-rounder", 100, "all-rounder", "srh", true],
  ["Harshal Patel", "India", "IN", "bowler", 100, "bowler", "srh", true],
  ["Kamindu Mendis", "Sri Lanka", "LK", "all-rounder", 75, "all-rounder", "srh", true],
  ["Ishan Kishan", "India", "IN", "wicket-keeper", 100, "wicket-keeper", "srh", true],
  ["Aniket Verma", "India", "IN", "batsman", 30, "uncapped", "srh", false],
  ["Smaran Ravichandran", "India", "IN", "batsman", 30, "uncapped", "srh", false],
  ["Salil Arora", "India", "IN", "wicket-keeper", 30, "uncapped", "srh", false],
  ["Harsh Dubey", "India", "IN", "all-rounder", 30, "uncapped", "srh", false],
  ["Shivang Kumar", "India", "IN", "all-rounder", 30, "uncapped", "srh", false],
  ["Krains Fuletra", "India", "IN", "all-rounder", 30, "uncapped", "srh", false],
  ["Ambrish", "India", "IN", "all-rounder", 30, "uncapped", "srh", false],
  ["Amit Kumar", "India", "IN", "all-rounder", 30, "uncapped", "srh", false],
  ["Jaydev Unadkat", "India", "IN", "bowler", 75, "bowler", "srh", true],
  ["Gerald Coetzee", "South Africa", "ZA", "bowler", 100, "bowler", "srh", true],
  ["Dilshan Madushanka", "Sri Lanka", "LK", "bowler", 50, "bowler", "srh", true],
  ["Zeeshan Ansari", "India", "IN", "bowler", 30, "uncapped", "srh", false],
  ["Eshan Malinga", "India", "IN", "bowler", 30, "uncapped", "srh", false],
  ["Sakib Hussain", "India", "IN", "bowler", 30, "uncapped", "srh", false],
  ["Onkar Tarmale", "India", "IN", "bowler", 30, "uncapped", "srh", false],
  ["Praful Hinge", "India", "IN", "bowler", 30, "uncapped", "srh", false],
  // === LSG ===
  ["Rishabh Pant", "India", "IN", "wicket-keeper", 200, "marquee", "lsg", true],
  ["Nicholas Pooran", "West Indies", "WI", "wicket-keeper", 200, "marquee", "lsg", true],
  ["Mitchell Marsh", "Australia", "AU", "all-rounder", 200, "marquee", "lsg", true],
  ["Mohammad Shami", "India", "IN", "bowler", 150, "marquee", "lsg", true],
  ["Aiden Markram", "South Africa", "ZA", "batsman", 100, "batsman", "lsg", true],
  ["Ayush Badoni", "India", "IN", "batsman", 75, "batsman", "lsg", true],
  ["Himmat Singh", "India", "IN", "batsman", 30, "uncapped", "lsg", false],
  ["Matthew Breetzke", "South Africa", "ZA", "batsman", 50, "batsman", "lsg", true],
  ["Akshat Raghuwanshi", "India", "IN", "batsman", 30, "uncapped", "lsg", false],
  ["Josh Inglis", "Australia", "AU", "wicket-keeper", 75, "wicket-keeper", "lsg", true],
  ["Mukul Choudhary", "India", "IN", "wicket-keeper", 30, "uncapped", "lsg", false],
  ["Abdul Samad", "India", "IN", "all-rounder", 50, "all-rounder", "lsg", true],
  ["Shahbaz Ahamad", "India", "IN", "all-rounder", 50, "all-rounder", "lsg", true],
  ["Arshin Kulkarni", "India", "IN", "all-rounder", 30, "uncapped", "lsg", false],
  ["Wanindu Hasaranga", "Sri Lanka", "LK", "all-rounder", 150, "all-rounder", "lsg", true],
  ["Avesh Khan", "India", "IN", "bowler", 100, "bowler", "lsg", true],
  ["Mayank Yadav", "India", "IN", "bowler", 75, "bowler", "lsg", true],
  ["Mohsin Khan", "India", "IN", "bowler", 50, "bowler", "lsg", true],
  ["Anrich Nortje", "South Africa", "ZA", "bowler", 150, "bowler", "lsg", true],
  ["M Siddharth", "India", "IN", "bowler", 50, "bowler", "lsg", true],
  ["Arjun Tendulkar", "India", "IN", "bowler", 30, "uncapped", "lsg", false],
  ["Akash Singh", "India", "IN", "bowler", 30, "uncapped", "lsg", false],
  ["Naman Tiwari", "India", "IN", "bowler", 30, "uncapped", "lsg", false],
  ["Prince Yadav", "India", "IN", "bowler", 30, "uncapped", "lsg", false],
  ["Digvesh Singh", "India", "IN", "bowler", 30, "uncapped", "lsg", false],
  // === GT ===
  ["Shubman Gill", "India", "IN", "batsman", 200, "marquee", "gt", true],
  ["Rashid Khan", "Afghanistan", "AF", "bowler", 200, "marquee", "gt", true],
  ["Kagiso Rabada", "South Africa", "ZA", "bowler", 200, "marquee", "gt", true],
  ["Jos Buttler", "England", "GB", "wicket-keeper", 200, "marquee", "gt", true],
  ["Sai Sudharsan", "India", "IN", "batsman", 100, "batsman", "gt", true],
  ["Shahrukh Khan", "India", "IN", "batsman", 75, "batsman", "gt", true],
  ["Glenn Phillips", "New Zealand", "NZ", "batsman", 75, "batsman", "gt", true],
  ["Connor Esterhuizen", "South Africa", "ZA", "wicket-keeper", 30, "uncapped", "gt", false],
  ["Rahul Tewatia", "India", "IN", "all-rounder", 75, "all-rounder", "gt", true],
  ["Washington Sundar", "India", "IN", "all-rounder", 100, "all-rounder", "gt", true],
  ["Jason Holder", "West Indies", "WI", "all-rounder", 100, "all-rounder", "gt", true],
  ["Nishant Sindhu", "India", "IN", "all-rounder", 30, "uncapped", "gt", false],
  ["Sai Kishore", "India", "IN", "bowler", 50, "bowler", "gt", true],
  ["Jayant Yadav", "India", "IN", "all-rounder", 50, "all-rounder", "gt", true],
  ["Mohd Arshad Khan", "India", "IN", "all-rounder", 30, "uncapped", "gt", false],
  ["Kumar Kushagra", "India", "IN", "wicket-keeper", 30, "uncapped", "gt", false],
  ["Anuj Rawat", "India", "IN", "wicket-keeper", 30, "uncapped", "gt", false],
  ["Tom Banton", "England", "GB", "wicket-keeper", 50, "wicket-keeper", "gt", true],
  ["Mohammed Siraj", "India", "IN", "bowler", 150, "bowler", "gt", true],
  ["Prasidh Krishna", "India", "IN", "bowler", 100, "bowler", "gt", true],
  ["Ishant Sharma", "India", "IN", "bowler", 75, "bowler", "gt", true],
  ["Manav Suthar", "India", "IN", "bowler", 30, "uncapped", "gt", false],
  ["Gurnoor Singh Brar", "India", "IN", "bowler", 30, "uncapped", "gt", false],
  ["Ashok Sharma", "India", "IN", "bowler", 30, "uncapped", "gt", false],
  ["Luke Wood", "England", "GB", "bowler", 50, "bowler", "gt", true],
  ["Kulwant Khejroliya", "India", "IN", "bowler", 30, "uncapped", "gt", false],
  ["Prithvi Raj Yarra", "India", "IN", "bowler", 30, "uncapped", "gt", false],
];

// Total: 257 players

function shuffleArray(array) {
    const shuffled = [...array];
    for (let i = shuffled.length - 1; i > 0; i--) {
        const j = Math.floor(Math.random() * (i + 1));
        [shuffled[i], shuffled[j]] = [shuffled[j], shuffled[i]];
    }
    return shuffled;
}

const CATEGORY_ORDER = ["marquee", "batsman", "bowler", "wicket-keeper", "all-rounder", "uncapped"];

let PLAYER_STATS;
try { PLAYER_STATS = require('../src/data/player-stats.json'); } catch(e) { PLAYER_STATS = {}; }

function getOrderedPlayers() {
    const grouped = {};
    CATEGORY_ORDER.forEach(c => grouped[c] = []);
    CRICKETER_DATA.forEach(p => {
        const cat = p[5];
        if (grouped[cat]) grouped[cat].push(p);
        else grouped["uncapped"].push(p);
    });
    const orderedData = [];
    CATEGORY_ORDER.forEach(cat => orderedData.push(...shuffleArray(grouped[cat])));
    return orderedData.map((data, index) => {
        const statsArr = PLAYER_STATS[data[0]] || [0, 0, 0];
        return {
            id: "p" + (index + 1),
            name: data[0], country: data[1], countryCode: data[2],
            role: data[3], basePrice: data[4], category: data[5],
            team2026: data[6] || null, isCapped: data[7] !== false,
            stats: { matches: statsArr[0], runs: statsArr[1], wickets: statsArr[2] },
        };
    });
}

function getShuffledPlayers() { return getOrderedPlayers(); }
module.exports = { getShuffledPlayers };
